format = " $character "


# Set the right format to the following:
# [ ğŸ“‚ ~ ] [ ğŸ¡ branch ] [ â° 10:10 ] ğŸ“
right_format="$directory$git_branch $time "



[character]
success_symbol = "[ğŸš€](fg:blue)"
error_symbol = "[ğŸ”¥](fg:red)"
vicmd_symbol = "[ğŸ˜¶](fg:green)"


[directory]
format = '[\[ ğŸ“‚ [$path](fg:yellow italic) \]](fg:yellow)'
disabled = false

[git_branch]
format = ' [\[ ğŸ¡ $branch \]](fg:blue bold)'
disabled = false

[time]
disabled = false
format = '[\[ â° [$time](fg:red italic) \]](fg:red)'
time_format = "%R" #%R for hh:mm, and %T for hh:mm:ss
use_12hr = true
